"""Page 2 — EDA.

Renders the EDA plots generated by ``src/data/eda.py`` (cached under
``results/figures/``) without re-running the (slow) EDA on every click.
"""

from __future__ import annotations

import streamlit as st

st.title("Exploratory Data Analysis")

st.info("Phase 10 implementation pending.")

# TODO(phase 10): show results/figures/class_distribution.png,
# correlation_heatmap.png, missing_value_audit.png, feature_distributions.png.
