"""Page 2 -- EDA.

Renders the EDA plots generated by ``src/data/eda.py`` (cached under
``results/figures/``).
"""

from __future__ import annotations

import streamlit as st

from dashboard._shared import figures_dir, load_eda_summary

st.title("Exploratory Data Analysis")

summary = load_eda_summary()
if summary is None:
    st.warning(
        "No EDA summary found. Run `python main.py --stage eda` first."
    )
    st.stop()

c1, c2, c3 = st.columns(3)
c1.metric("Rows", f"{summary.get('shape', [0])[0]:,}")
c2.metric("Features", summary.get("n_features", "-"))
c3.metric("Duplicate rows", summary.get("duplicate_row_count", "-"))

with st.expander("Dtype breakdown"):
    st.write(summary.get("dtype_counts", {}))

st.subheader("Class distribution")
img = figures_dir() / "class_distribution.png"
if img.exists():
    st.image(str(img), use_container_width=True)
else:
    st.info("Re-run `--stage eda` to regenerate the class-distribution plot.")

st.subheader("Missing-value audit")
img = figures_dir() / "missing_value_audit.png"
if img.exists():
    st.image(str(img), use_container_width=True)

st.subheader("Feature correlation (top-25 by variance)")
img = figures_dir() / "correlation_heatmap.png"
if img.exists():
    st.image(str(img), use_container_width=True)

st.subheader("Feature distributions by class")
img = figures_dir() / "feature_distributions.png"
if img.exists():
    st.image(str(img), use_container_width=True)
