"""Page 2 -- Exploratory Data Analysis."""

from __future__ import annotations

import streamlit as st

from dashboard._shared import figures_dir, load_eda_summary
from dashboard._style import apply_style, hero, pill, section

st.set_page_config(page_title="EDA", page_icon=":mag:", layout="wide")
apply_style()

hero(
    "Exploratory Data Analysis",
    "Pre-modelling sanity check -- class balance, missing-value audit, correlations.",
)

summary = load_eda_summary()
if summary is None:
    st.warning(
        "No EDA summary found. Run `python main.py --stage eda` first."
    )
    st.stop()

# --- top stats ---------------------------------------------------------
shape = summary.get("shape", [0, 0])
c1, c2, c3, c4 = st.columns(4)
c1.metric("Rows", f"{shape[0]:,}")
c2.metric("Columns", f"{shape[1]:,}")
c3.metric("Features", summary.get("n_features", "—"))
c4.metric("Duplicate rows", f"{summary.get('duplicate_row_count', 0):,}")

# Status pills.
inf_total = summary.get("infinite_total", 0)
miss_total = summary.get("missing_total", 0)
pills = " &nbsp; ".join([
    pill(f"{miss_total:,} missing cells", "warn" if miss_total else "success"),
    pill(f"{inf_total:,} ±Inf values",    "warn" if inf_total else "success"),
    pill(f"mode: {summary.get('classification_mode', '?')}", "accent"),
])
st.markdown(pills, unsafe_allow_html=True)

# --- tabbed EDA --------------------------------------------------------
section("EDA visualisations", "Generated by `python main.py --stage eda`")

tab_class, tab_missing, tab_corr, tab_feat = st.tabs(
    ["Class balance", "Missing values", "Correlation heatmap", "Feature distributions"]
)

with tab_class:
    p = figures_dir() / "class_distribution.png"
    st.caption("Class distribution after label mapping (log-scaled).")
    if p.exists():
        st.image(str(p), use_container_width=True)
    else:
        st.info("Re-run `--stage eda` to regenerate this plot.")

with tab_missing:
    p = figures_dir() / "missing_value_audit.png"
    st.caption("Top-20 columns by missing-value count after cleaning.")
    if p.exists():
        st.image(str(p), use_container_width=True)
    else:
        st.info("Re-run `--stage eda` to regenerate this plot.")

with tab_corr:
    p = figures_dir() / "correlation_heatmap.png"
    st.caption("Pearson correlation across the 25 most-varying features.")
    if p.exists():
        st.image(str(p), use_container_width=True)
    else:
        st.info("Re-run `--stage eda` to regenerate this plot.")

with tab_feat:
    p = figures_dir() / "feature_distributions.png"
    st.caption("Violin plots of the 6 most discriminative features, split by class.")
    if p.exists():
        st.image(str(p), use_container_width=True)
    else:
        st.info("Re-run `--stage eda` to regenerate this plot.")

# --- detail expanders --------------------------------------------------
with st.expander("Dtype breakdown"):
    st.write(summary.get("dtype_counts", {}))
with st.expander("Missing-value detail (top-5 cols)"):
    st.write(summary.get("missing_per_column_top5", {}))
with st.expander("Columns containing +/-Inf"):
    st.write(summary.get("infinite_columns", []))
